In [2]:
#Import dependecies 
import pandas as pd
import matplotlib as plt

In [3]:
#Read Csv file into a DataFrame 
file = pd.read_csv("Resources/clean_netflix_shows.csv")

file

,Unnamed: 0,Title,Genre,Premiere,Runtime,IMDB Score,Language,Omdb Review Score,Omdb Review Count,Month,Year,Financial Quarter
0,0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese,2.5,"1,515",August,2019,3
1,1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish,3.9,31,August,2020,3
2,2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian,2.6,"1,201",December,2019,4
3,3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English,3.2,"32,162",January,2018,1
4,4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi,3.4,"1,048",October,2020,4
...,...,...,...,...,...,...,...,...,...,...,...,...
497,497,Taylor Swift: Reputation Stadium Tour,Concert Film,"December 31, 2018",125,8.4,English,8.4,"4,349",December,2018,4
498,498,Winter on Fire: Ukraine's Fight for Freedom,Documentary,"October 9, 2015",91,8.4,English/Ukranian/Russian,8.4,"13,353",October,2015,4
499,499,Springsteen on Broadway,One-man show,"December 16, 2018",153,8.5,English,8.5,"2,001",December,2018,4
500,500,Emicida: AmarElo - It's All For Yesterday,Documentary,"December 8, 2020",89,8.6,Portuguese,8.6,"1,136",December,2020,4
501,501,David Attenborough: A Life on Our Planet,Documentary,"October 4, 2020",83,9.0,English,9.0,"28,028",October,2020,4

In [4]:
year_count = file["Year"].value_counts()

year_count

2020    145
2019    109
2018     90
2017     63
2021     56
2016     29
2015      9
2014      1
Name: Year, dtype: int64

In [10]:
grouped_yearcount = file.groupby("Year")

print(grouped_yearcount)

grouped_count = grouped_yearcount.size()

grouped_count.head(10)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000016FED15CCD0>

Year
2014      1
2015      9
2016     29
2017     63
2018     90
2019    109
2020    145
2021     56
dtype: int64

In [11]:
average_year_runtime = file.groupby("Year")["Runtime"].mean()

average_year_runtime.head(10)

Year
2014     81.000000
2015     90.444444
2016     92.758621
2017     92.793651
2018     94.844444
2019     88.082569
2020     94.262069
2021    103.267857
Name: Runtime, dtype: float64