# How runtime affects the scores on an IMDB

In [1]:
#import dependecies
import pandas as pd
import matplotlib as plt

In [2]:
#read the csv into dataframe
net_df = pd.read_csv('../../Resources/netflix_omdb.csv',index_col=0)

In [3]:
#display dataframe
net_df

,Title,Genre,Premiere,Runtime,IMDB Score,Language,Omdb Review Score,Omdb Review Count,Month,Year,Financial Quarter
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese,2.5,"1,515",August,2019,3
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish,3.9,31,August,2020,3
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian,2.6,"1,201",December,2019,4
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English,3.2,"32,162",January,2018,1
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi,3.4,"1,048",October,2020,4
...,...,...,...,...,...,...,...,...,...,...,...
579,Taylor Swift: Reputation Stadium Tour,Concert Film,"December 31, 2018",125,8.4,English,8.4,"4,349",December,2018,4
580,Winter on Fire: Ukraine's Fight for Freedom,Documentary,"October 9, 2015",91,8.4,English/Ukranian/Russian,8.4,"13,353",October,2015,4
581,Springsteen on Broadway,One-man show,"December 16, 2018",153,8.5,English,8.5,"2,001",December,2018,4
582,Emicida: AmarElo - It's All For Yesterday,Documentary,"December 8, 2020",89,8.6,Portuguese,8.6,"1,136",December,2020,4
583,David Attenborough: A Life on Our Planet,Documentary,"October 4, 2020",83,9.0,English,9.0,"28,028",October,2020,4

## Clean the dataframe

In [4]:
# find the null values in dataframe
null_df = net_df[net_df.isna().any(axis=1)]
null_df

,Title,Genre,Premiere,Runtime,IMDB Score,Language,Omdb Review Score,Omdb Review Count,Month,Year,Financial Quarter
6,Leyla Everlasting,Comedy,"December 4, 2020",112,3.7,Turkish,NaN,NaN,December,2020,4
28,The Misadventures of Hedi and Cokeman,Comedy,"February 10, 2021",99,4.5,French,NaN,NaN,February,2021,1
29,5 Star Christmas,Comedy,"December 7, 2018",95,4.6,Italian,NaN,NaN,December,2018,4
32,Paris Is Us,Romance drama,"February 22, 2019",83,4.6,French,NaN,NaN,February,2019,1
33,Porta dos Fundos: The First Temptation of Christ,Comedy,"December 3, 2019",46,4.6,Portuguese,NaN,NaN,December,2019,4
...,...,...,...,...,...,...,...,...,...,...,...
545,Rolling Thunder Revue: A bob Dylan Story by Ma...,Documentary,"June 12, 2019",144,7.6,English,NaN,NaN,June,2019,2
555,Crip Camp: A Disability Revolution,Documentary,"March 25, 2020",108,7.7,English,NaN,NaN,March,2020,1
558,Road to Roma,Making-of,"February 11, 2020",72,7.7,Spanish,NaN,NaN,February,2020,1
567,Struggle: The Life and Lost Art of Szukaiski,Documentary,"December 21, 2018",105,8.0,English,NaN,NaN,December,2018,4
575,The Three Deaths of Marisela Escobedo,Documentary,"October 14, 2020",109,8.2,Spanish,NaN,NaN,October,2020,4

In [5]:
#dropping the null values
new_net_df = (net_df.dropna(how= 'any')).reset_index(drop = True)
new_net_df

,Title,Genre,Premiere,Runtime,IMDB Score,Language,Omdb Review Score,Omdb Review Count,Month,Year,Financial Quarter
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese,2.5,"1,515",August,2019,3
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish,3.9,31,August,2020,3
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian,2.6,"1,201",December,2019,4
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English,3.2,"32,162",January,2018,1
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi,3.4,"1,048",October,2020,4
...,...,...,...,...,...,...,...,...,...,...,...
497,Taylor Swift: Reputation Stadium Tour,Concert Film,"December 31, 2018",125,8.4,English,8.4,"4,349",December,2018,4
498,Winter on Fire: Ukraine's Fight for Freedom,Documentary,"October 9, 2015",91,8.4,English/Ukranian/Russian,8.4,"13,353",October,2015,4
499,Springsteen on Broadway,One-man show,"December 16, 2018",153,8.5,English,8.5,"2,001",December,2018,4
500,Emicida: AmarElo - It's All For Yesterday,Documentary,"December 8, 2020",89,8.6,Portuguese,8.6,"1,136",December,2020,4
501,David Attenborough: A Life on Our Planet,Documentary,"October 4, 2020",83,9.0,English,9.0,"28,028",October,2020,4

In [6]:
# sorting the dataframe on runtime 
new_net_df.sort_values(by=['Runtime'])

,Title,Genre,Premiere,Runtime,IMDB Score,Language,Omdb Review Score,Omdb Review Count,Month,Year,Financial Quarter
35,Sol Levante,Anime / Short,"April 2, 2020",4,4.7,English,4.7,422,April,2020,2
353,Cops and Robbers,Animation / Short,"December 28, 2020",7,6.9,English,6.3,701,December,2020,4
274,Canvas,Animation / Short,"December 11, 2020",9,6.5,English,6.5,"2,012",December,2020,4
54,American Factory: A Conversation with the Obamas,Aftershow / Interview,"August 21, 2019",10,5.2,English,5.2,247,August,2019,3
423,Zion,Documentary,"August 10, 2018",11,7.2,English,7.2,"1,072",August,2018,3
...,...,...,...,...,...,...,...,...,...,...,...
212,Citation,Drama,"November 6, 2020",151,6.2,English,6.2,866,November,2020,4
240,The Forest of Love,Drama,"October 11, 2019",151,6.3,Japanese,6.8,300,October,2019,4
499,Springsteen on Broadway,One-man show,"December 16, 2018",153,8.5,English,8.5,"2,001",December,2018,4
276,Da 5 Bloods,War drama,"June 12, 2020",155,6.5,English,6.5,"46,333",June,2020,2
481,The Irishman,Crime drama,"November 27, 2019",209,7.8,English,7.8,"342,106",November,2019,4

In [7]:
new_net_df.to_csv('../../Resources/clean_netflix_shows.csv')