In [1]:
import pandas as pd
import numpy as np

In [2]:
file = "../Resources/netflix_omdb"
netflix_omdb_df = pd.read_csv(file, index_col=0)
netflix_omdb_df

,Title,Genre,Premiere,Runtime,IMDB Score,Language,Omdb Review Score,Omdb Review Count
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese,2.5,"1,515"
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish,3.9,31
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian,2.6,"1,201"
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English,3.2,"32,162"
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi,3.4,"1,048"
...,...,...,...,...,...,...,...,...
579,Taylor Swift: Reputation Stadium Tour,Concert Film,"December 31, 2018",125,8.4,English,8.4,"4,349"
580,Winter on Fire: Ukraine's Fight for Freedom,Documentary,"October 9, 2015",91,8.4,English/Ukranian/Russian,8.4,"13,353"
581,Springsteen on Broadway,One-man show,"December 16, 2018",153,8.5,English,8.5,"2,001"
582,Emicida: AmarElo - It's All For Yesterday,Documentary,"December 8, 2020",89,8.6,Portuguese,8.6,"1,136"
583,David Attenborough: A Life on Our Planet,Documentary,"October 4, 2020",83,9.0,English,9.0,"28,028"

In [6]:
#return month of each premiere
netflix_omdb_df["Month"] = netflix_omdb_df["Premiere"].str.split().str[0].str.strip()
netflix_omdb_df["Year"] = netflix_omdb_df["Premiere"].str.split().str[-1].str.strip()

#list financial quarters to sort to
q1 = ["January", "February", "March"]  
q2 = ["April","May","June"]
q3 = ["July","August","September"]  
q4 = ["October", "November", "December"]

#Add New Column
netflix_omdb_df["Financial Quarter"] = np.nan

for index, row in netflix_omdb_df.iterrows():
    key = row["Month"]
    if key in q1:
        netflix_omdb_df.loc[index, "Financial Quarter"] = "1"
    elif key in q2:
        netflix_omdb_df.loc[index, "Financial Quarter"] = "2"
    elif key in q3:
        netflix_omdb_df.loc[index, "Financial Quarter"] = "3"
    elif key in q4:
        netflix_omdb_df.loc[index, "Financial Quarter"] = "4"
        
netflix_omdb_df

,Title,Genre,Premiere,Runtime,IMDB Score,Language,Omdb Review Score,Omdb Review Count,Month,Year,Financial Quarter
6,Leyla Everlasting,Comedy,"December 4, 2020",112,3.7,Turkish,NaN,NaN,December,2020,4
7,The Last Days of American Crime,Heist film/Thriller,"June 5, 2020",149,3.7,English,3.7,"10,245",June,2020,2
9,Sardar Ka Grandson,Comedy,"May 18, 2021",139,4.1,Hindi,4.2,"3,955",May,2021,2
28,The Misadventures of Hedi and Cokeman,Comedy,"February 10, 2021",99,4.5,French,NaN,NaN,February,2021,1
29,5 Star Christmas,Comedy,"December 7, 2018",95,4.6,Italian,NaN,NaN,December,2018,4
...,...,...,...,...,...,...,...,...,...,...,...
558,Road to Roma,Making-of,"February 11, 2020",72,7.7,Spanish,NaN,NaN,February,2020,1
567,Struggle: The Life and Lost Art of Szukaiski,Documentary,"December 21, 2018",105,8.0,English,NaN,NaN,December,2018,4
572,Disclosure: Trans Lives on Screen,Documentary,"June 19, 2020",107,8.2,English,8.2,"4,503",June,2020,2
575,The Three Deaths of Marisela Escobedo,Documentary,"October 14, 2020",109,8.2,Spanish,NaN,NaN,October,2020,4
578,Ben Platt: Live from Radio City Music Hall,Concert Film,"May 20, 2020",85,8.4,English,8.4,404,May,2020,2

In [8]:
netflix_omdb_df = netflix_omdb_df[netflix_omdb_df.isna().any(axis=1)]
netflix_omdb_df["Financial Quarter"].value_counts()

4    32
2    18
1    17
3    15
Name: Financial Quarter, dtype: int64

In [9]:
netflix_omdb_df.to_csv("../Resources/netflix_omdb")